# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: tab
    width: 1

SelectorFormat:
    enabled: true
    convention: classic_BEM